# Generated by Django 3.1 on 2020-09-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_categoria_comentario_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Destaque'),
        ),
    ]
