# Generated by Django 3.1 on 2020-10-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_auto_20200925_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='acessos',
            field=models.IntegerField(default=0, verbose_name='Acessos'),
        ),
    ]
