# Generated by Django 3.1 on 2020-10-19 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0012_remove_post_destaque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['data'], 'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AddField(
            model_name='comentario',
            name='comentario_pai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='inicio.comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='inicio.post', verbose_name='Postagem'),
        ),
    ]
