# Generated by Django 3.1 on 2020-10-20 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0016_auto_20201019_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario_pai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='inicio.comentario', verbose_name='Em resposta a'),
        ),
    ]
