# Generated by Django 3.1 on 2020-10-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0018_auto_20201019_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='conteudo',
            field=models.TextField(max_length=5000, verbose_name='Conteúdo'),
        ),
    ]
