# Generated by Django 3.1 on 2020-10-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0019_auto_20201019_2341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
