# Generated by Django 3.1 on 2020-10-22 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0021_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='curtidas',
            field=models.ManyToManyField(related_name='posts_curtidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
