# Generated by Django 3.1 on 2020-10-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0022_post_curtidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='aprovado',
            field=models.BooleanField(default=False, verbose_name='Aprovado'),
        ),
    ]
