# Generated by Django 3.1 on 2020-11-03 23:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0024_auto_20201024_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='posts_curtidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
