# Generated by Django 3.1 on 2020-11-10 11:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0025_auto_20201103_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=tinymce.models.HTMLField(verbose_name='Conteúdo'),
        ),
    ]
