# Generated by Django 3.1 on 2020-09-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20200903_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='newsletter',
            field=models.BooleanField(default=True, verbose_name='Cadastrado na Newsletter'),
        ),
    ]
