# Generated by Django 3.1 on 2020-09-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfis/%Y/%m/%d', verbose_name='Foto de Perfil'),
        ),
    ]
